### PR TITLE
Respect negated patterns in .gitignore

### LINKED ISSUE #2: Respect negated .gitignore patterns
Show nodes that match negated patterns in `.gitignore`. For example:

```
!this_file_must_be_shown_in_nerdtree
```

### PR DESCRIPTION
**Pull request by bagrat**
Fixes #2

### CODE REVIEW

**Comment by bagrat** [comment]
Additional issue about paths containing spaces. In that case the flagging does not work, as an exception is being thrown.

Did not report this issue, fixed in this PR.

**Comment by albfan** [comment]
I have added a test suite https://github.com/albfan/nerdtree-git-plugin/commit/4fc3a16dbd68fe3cb5fe160aacd8a0a9b96d04d5 to allow TDD develop.

Then I have rebased your changes against it and it correctly not fail as expected.

If you want you can rebase yourself and remove the `"""" failed` mark to test1, so it correctly resolves issue #2.

As an example I have upload a quick and dirty fix for this issue (mostly the same as you) https://github.com/albfan/nerdtree-git-plugin/tree/negative

Please merge or rebase fixes against test suite and add test for solutions provided. if this is to much overhead I will apply your changes in next days.

I'm now designing the travis environment for CI

**Comment by albfan** [comment]
See test suite results here:

[master, failed test1 expected](https://travis-ci.org/albfan/nerdtree-git-plugin/builds/89565977)
[negative branch, test1 ok](https://travis-ci.org/albfan/nerdtree-git-plugin/builds/89566014)

You will see if you pass test suite here automatically

http://stackoverflow.com/questions/15825770/github-pull-request-good-to-merge

or here

https://travis-ci.org/albfan/nerdtree-git-plugin/pull_requests

**Comment by albfan** [comment]
Funnily enough, the new test suite shows my solution for negative patterns was wrong. I have rebased your work on top of test suite, and added a failed test for repos with spaces. Your proposal works, so I pick it too.

Many many thanks, lot of people will be thankful for this, and finally this forces me to add test suite.

If you see all your work added please close this PR. I will do in a couple of days otherway

**Comment by bagrat** [comment]
First of all many thanks go to you for the awesome plugin.

Sorry for the late response. I have reviewed the changes, and all seems to be fine. Now is there anything needed from my side or we can just close the PR?

**Comment by albfan** [comment]
Since all changes are integrated, and you're fine with the rebase, just close this.

**Pull request closed without merging**
