### PR TITLE
Hide folders for patterns ending with `/`

### PR DESCRIPTION
**Pull request by bagrat**
When there are patterns in .gitignore ending with /, matching directories are not hidden in NERDTree. This PR solves that issue by removing the / suffix from the pattern beforehand.

@albfan please review

### CODE REVIEW

**Comment by albfan** [comment]
Great. just let me add a test for this (you can do it yourself if you want too) and merge

**Comment by albfan** [comment]
@n9code I just pushed the failed test about dir patterns (test7) can you finish it? just rebase this on top of master and remove failed mark on test7.vim (fix whatever needs to be fixed) I can do later but would be great if you do so

**Comment by bagrat** [comment]
@albfan sorry for such a delay, but I'm afraid I won't have time to resume this.

**Comment by albfan** [comment]
Ok I will try myself

**Pull request closed without merging**
