### PR TITLE
Hide folders for patterns ending with `/`

### PR DESCRIPTION
**Pull request by bagrat**
When there are patterns in `.gitignore` ending with `/`, matching directories are not hidden in NERDTree. This PR solves that issue by removing the `/` suffix from the pattern beforehand.

### CODE REVIEW

**Review by jlipps — APPROVED** [review]

**Comment by albfan** [comment]
Seems great @n9code , but avoid whitespace change. Is clearly bad indented (and exist trailing spaces, but that is not part of the fix)

@jlipps How is it that you approve this change? I'm new to these code review features and I would like to know more about it.

If you use this fork I suggest to try to PR upstream. We all can collaborate on that

**Comment by bagrat** [comment]
@albfan do you mean remove the whitespace changes from this PR? I did not touch identation actually, just removed trailing spaces.

**Comment by albfan** [comment]
@n9code Yes. It would help to PR to upstream only precise changes.

**Comment by bagrat** [comment]
Created #12 with no whitespace tweaks.

**Pull request closed without merging**
